[package]
name = "dual-spacetime-simulator"
version = "0.1.0"
edition = "2024"

[dependencies]
egui_winit_vulkano = "0.28"
egui = "0.31"
winit = "0.30"
vulkano = "0.35"
vulkano-shaders = "0.35"
vulkano-util = "0.35"
bytemuck = "1.23"
anyhow  = "1.0"
rand = "0.8"

[dev-dependencies]
mockall = "0.13"
cgmath = "0.18"

[profile.release]
codegen-units = 1
lto = true
panic = "abort"